### ISSUE TITLE
Button type not working properly

### ISSUE THREAD

**Issue by Abdallah-Awwad** [karamokoisrael/directus-extension-flow2pdf#2]
When I tried to change the `Button type` in the interface, I can't see the color of the button changed as expected. 

![image](https://github.com/karamokoisrael/directus-extension-flow2pdf/assets/129249191/87da79da-ecae-4548-8ebd-6a9f80fcf7c0)

**Comment by karamokoisrael** [comment]
You're right, I'm going to solve this issue.

**Comment by karamokoisrael** [comment]
Problem solved in the latest version of the extension
